In [2]:
import numpy as np

In [3]:
arr = np.arange(4)

In [4]:
arr[0:5]  # не вызовет ошибку, а вызовет столько сколько сможет

array([0, 1, 2, 3])

In [5]:
new = np.array([4, 7, 'альбом', ['1', '2', '3']], dtype=object)

In [6]:
new

array([4, 7, 'альбом', list(['1', '2', '3'])], dtype=object)

In [8]:
m1 = np.arange(10)

In [10]:
m2 = m1[3:6].copy()

In [12]:
m2

array([3, 4, 5])

In [14]:
m2d = np.array([[1, 2, 3], [4, 5, 6]])

In [16]:
m2d.shape

(2, 3)

In [19]:
m2d[1, 1]

5

In [21]:
m3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [24]:
m3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
m3d.shape

(2, 2, 3)

In [28]:
m3d[1, 1, 1]

11

In [30]:
m3d[0] = 0

In [33]:
m3d

array([[[ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [35]:
m2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])

In [38]:
m2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [40]:
m2d[2:4]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [42]:
m2d[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [44]:
m2d[:, 0]

array([ 1,  5,  9, 13, 17])

In [48]:
m2d[:][2]

array([ 9, 10, 11, 12])

In [50]:
m2d[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [53]:
m2d[3:, 2:]

array([[15, 16],
       [19, 20]])

In [55]:
m2d[1:4, 1:3]

array([[ 6,  7],
       [10, 11],
       [14, 15]])

In [57]:
m = np.array([5, 4, 3, 6, 8, 10])

In [59]:
m > 5

array([False, False, False,  True,  True,  True])

In [61]:
mask = m > 5

In [63]:
mask

array([False, False, False,  True,  True,  True])

In [65]:
m[mask]

array([ 6,  8, 10])

In [67]:
m[m > 5]

array([ 6,  8, 10])

In [69]:
n = np.arange(5)

In [71]:
mask = [False, True, True, False, True]

In [76]:
k = n[mask]

In [78]:
k[0] = 19

In [80]:
k

array([19,  2,  4])

In [81]:
n

array([0, 1, 2, 3, 4])