In [16]:
import numpy as np

In [4]:
lst = list(range(1_000_000))

In [7]:
len(lst)

1000000

In [8]:
arr = np.arange(1_000_000)

In [10]:
arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [14]:
%time for _ in range(10): lst2 = [x ** 2 for x in lst]  # мы засекаем время выполнения

CPU times: total: 3.05 s
Wall time: 3.06 s


In [18]:
%time for _ in range(10): arr2 = arr ** 2

CPU times: total: 15.6 ms
Wall time: 20 ms


In [23]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable


In [24]:
!pip show numpy

Name: numpy
Version: 1.21.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: c:\programdata\anaconda3\lib\site-packages
Requires: 
Required-by: xarray, tifffile, tables, statsmodels, seaborn, scipy, scikit-learn, scikit-image, PyWavelets, pyerfa, patsy, pandas, numexpr, numba, mkl-random, mkl-fft, matplotlib, imageio, imagecodecs, hvplot, holoviews, h5py, gensim, datashape, datashader, daal4py, Bottleneck, bokeh, bkcharts, astropy


In [25]:
lst = [1, 2, 3, 4.5]

In [27]:
arr = np.array(lst)

In [30]:
arr

array([1. , 2. , 3. , 4.5])

In [39]:
lst1 = [[1, 2, 3], [4, 5, 6]]
lst1

[[1, 2, 3], [4, 5, 6]]

In [41]:
arr1 = np.array(lst1)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr1.shape

(2, 3)

In [44]:
arr.dtype

dtype('float64')

In [46]:
arr1.dtype

dtype('int32')

In [50]:
arr2 = np.zeros(5)
arr2.dtype

dtype('float64')

In [52]:
arr2

array([0., 0., 0., 0., 0.])

In [54]:
arr3 = np.zeros((3, 2, 1))
arr3

array([[[0.],
        [0.]],

       [[0.],
        [0.]],

       [[0.],
        [0.]]])

In [58]:
arr4 = np.ones((4, 5))
arr4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [60]:
arr5 = np.ones([2, 4])
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
arr6 = np.full(3, 18)
arr6

array([18, 18, 18])

In [64]:
arr7 = np.full((3, 3), 'Love')
arr7

array([['Love', 'Love', 'Love'],
       ['Love', 'Love', 'Love'],
       ['Love', 'Love', 'Love']], dtype='<U4')

In [66]:
arr7 = np.full((3, 3), -3.14)
arr7

array([[-3.14, -3.14, -3.14],
       [-3.14, -3.14, -3.14],
       [-3.14, -3.14, -3.14]])

In [69]:
arr8 = np.arange(15)
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])