In [2]:
import numpy as np

In [6]:
arr = np.arange(10)

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr.dtype

dtype('int32')

In [12]:
arr1 = np.array([1, 2, 3, 4 ,5], dtype=np.float64)

In [14]:
arr1

array([1., 2., 3., 4., 5.])

In [16]:
arr1.dtype

dtype('float64')

In [18]:
arr2 = arr1.astype(np.int64)

In [20]:
arr2

array([1, 2, 3, 4, 5], dtype=int64)

In [22]:
arr3 = np.array([1.2, 3.4, 5.6, 7.8, 9.0])

In [24]:
arr4 = arr3.astype(np.int32)

In [26]:
arr4

array([1, 3, 5, 7, 9])

In [30]:
arr5 = np.array(['1.5', '-2.4', '3', '-8', '-13_285.13'])

In [32]:
arr5

array(['1.5', '-2.4', '3', '-8', '-13_285.13'], dtype='<U10')

In [34]:
arr6 = arr5.astype(np.float64)

In [36]:
arr6

array([ 1.500000e+00, -2.400000e+00,  3.000000e+00, -8.000000e+00,
       -1.328513e+04])

In [39]:
arr7 = arr6.astype(arr2.dtype)

In [41]:
arr7

array([     1,     -2,      3,     -8, -13285], dtype=int64)

In [43]:
lst = [1, 2, 3, 4]

In [45]:
arr8 = np.array([1, 2, 3, 4])

In [47]:
arr8 * 2

array([2, 4, 6, 8])

In [49]:
arr9 = arr8 * arr8

In [51]:
arr9

array([ 1,  4,  9, 16])

In [61]:
arr10 = arr9 * arr9

In [63]:
arr10

array([         1,          0, -919996767,          0], dtype=int32)

In [65]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
b = a.reshape(3, 3)

In [69]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
b[2, 0]

7

In [77]:
b + 1

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [78]:
b

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [80]:
arr11 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
arr11 + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
arr11 - 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [89]:
arr11 ** 10

array([         1,       1024,      59049,    1048576,    9765625,
         60466176,  282475249, 1073741824, -808182895], dtype=int32)

In [91]:
arr12 = np.array([[1, 2, 3], [4, 5, 6]])

In [93]:
arr12


array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
arr12 / 3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [97]:
lst1 = [2, 4]

In [99]:
lst2 = [1, 3, 5, 7]

In [102]:
lst1 > lst2

True

In [106]:
arr13 = arr6 > arr7

In [108]:
arr13.dtype

dtype('bool')

In [113]:
x = np.arange(10)

In [115]:
x[1:7] = 3

In [117]:
x

array([0, 3, 3, 3, 3, 3, 3, 7, 8, 9])

In [119]:
# Напишите функцию, которая на основе существующего списка создает numpy массив с типом float64
import numpy as np

def solution(lst):
    arr = np.array(lst, dtype='float64')
    return arr

In [120]:
# К вам в распоряжение поступает массив arr с типом float64. Преобразуйте, пожалуйста, в int32
import numpy as np

def solution(arr):
    arr = arr.astype('int32')
    return arr